version: "3"

services:
  test_db:
    container_name: test_database_checkpoint
    image: "mysql:8.0.22"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=checkpoint_4_test
    tmpfs: /var/lib/mysql
  db:
    image: "mysql:8.0.22"
    command: --default-authentication-plugin=mysql_native_password
    container_name: database_checkpoint
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=checkpoint_4
    volumes:
      - p3-db:/var/lib/mysql
  server:
    container_name: server
    depends_on:
      - db
    build: "."
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=checkpoint_4
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "5000:5000"
    command: 'bash -c "chmod u+x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh db:3306 && npm i && npm run start:watch"'

volumes:
  p3-db:
